### ISSUE TITLE
Sprint 4: Develop Spell Check Metrics

### ISSUE THREAD

**Issue by MaxCunningham19** [MaxCunningham19/legal_spellcheck#102]
When a user validates an entire document we want to be able to display a document metrics screen this will include several metrics some examples can be found below. The tasks involved with issue will be:
 1. Researching possible metrics
 2. Deciding which metrics to use
 3. Developing the function(s) to calculate these metrics
 4. Developing the API endpoint that will return these metrics (this should be included in the check entire document endpoint)

Some Examples:
* Total Spelling Errors (int)
* Problem Paragraphs (list int - ranked top 3 paragraphs with most errors)
* Document Health (float 0-1 - some calculation of number of misspelt words, total word count, and confidence of suggestion to top answer e.g. ```Sum(error_i*(1-top_suggestion_i))/word_count)```
* Common Misspellings (list string - top 3 misspelt words)
* percentage of errors (float 0-1 - could be broken into categories bad, poor, correct where correct is percentage of correct words,  poor was words with a suggestion rating 0.7-0.99, bad is all errors with a rating <0.7)
* ECT

This is not a complete list just some example and others can be added and these do not have to be used.

**Comment by petamar** [comment]
Some examples that are added into side bar now are:
-showing total number of mistakes
-showing percentage of mistakes in text
-showing most common mistakes
-showing problem paragraphs

**Comment by petamar** [comment]
metrics completed
