### ISSUE TITLE
Sprint 4: Create Metrics Screen/Popup

### ISSUE THREAD

**Issue by MaxCunningham19** [MaxCunningham19/legal_spellcheck#103]
This is dependent on the metrics chosen in issue #102.

When a decision is made on which metrics to develop then the FE team can decide how best to display these metrics and develop the screen/popup as they see fit.

**Comment by petamar** [comment]
Added comment in #102 that describes functionality chosen.

This can be changed easily according to what we decide. In my opinion we should wait for backend and see which functionalities are not that hard to implement with data being passed from api.  This is not connected to backend yet.
