### ISSUE TITLE
Sprint 1: Research AWS functionality for Spellcheck

### ISSUE THREAD

**Issue by MaxCunningham19** [MaxCunningham19/legal_spellcheck#16]
# Research and Write up a Document for how we can use AWS
## emphasis on ML, spellcheck, dbs, and hosting applications.

This will involve writing up all research into the below document. 

[AWS Research Document](https://docs.google.com/document/d/1nXcVFtsD6UzTUws3UkUqo2zteCBrSl92z9he2oh0zLg/edit?usp=sharing)

---

Some points of note are look into AWS Kendra, pick out a few AWS services that may be useful. And for all of the above try find tutorials/how tis using python (if possible). More resources can be found below.

### Resources:

* [AWS functions](https://www.youtube.com/watch?v=JIbIYCM48to)
* [Hosting on AWS](https://www.youtube.com/watch?v=8eGRJCYSUsU)
* [AWS Site](https://aws.amazon.com)
* [Amazon Kendra](https://aws.amazon.com/kendra/)

**Comment by EssienThompson** [comment]
I have added some suggestion as to which AWS functions we could utilize in our spell check and even found a [tutorial](https://youtu.be/mls8tiiI3uc) which helps us host the react app using AWS S3

**Comment by MaxCunningham19** [comment]
Hey, The document is looking good so far.

I think it would be valuable to do some more research into Amazon Kendra Specifically. It would be great to add some more specific information in this area e.g. code snippets, tutorial videos, detailed descriptions of how to use it ect. would that be possible

i.e something like the below

---
Amazon Kendra Use cases:
- building ml language models
- next word prediction
- auto completion
- spellchecking via ml modeling

What we would need to use it:
- large amount of legal document data
     OR
- use the in-built English language support which is not legal specific

Simple Code example of how to use it:
```
import AmazonKendra as AWS
spellchecked_document = AWS.engSpellCheck(document)
the_same = compare(spellchecked_document,document);
if not the_same:
   print("has spelling mistakes")
else: 
  print("no mistakes")

```
---

@thompsdy @EssienThompson

**Comment by thompsdy** [comment]
Updated the Document with some more AWS Services I think would be useful for our application.

I also went through a tutorial of how to set up static hosting of our application using S3, Route 53 and CloudFront.
