### ISSUE TITLE
Sprint 1 & 2: Add Decals and Sections to NavBar

### ISSUE THREAD

**Issue by MaxCunningham19** [MaxCunningham19/legal_spellcheck#19]
# Add in the Buttons for Sections to the NavBar section (on the left).

This will mean creating the css of the navbar, creating each of the sections; myDocuments, Browse, Create, Upload ect.

**Comment by max-romagnoli** [comment]
Requesting an edit in the issue to reflect the updated prototype.
Sections are now reduced to two: My Documents and Browse.

**Comment by MaxCunningham19** [comment]
The priority on this has been updated to reflect that it is needed for #53 #54 #55

**Comment by petamar** [comment]
@max-romagnoli @MaxCunningham19 just implemented it in new pr... might not be extra beautiful but we can have chat about design later this week
