### ISSUE TITLE
Sprint 2: Add toggle functionality to Header buttons

### ISSUE THREAD

**Issue by max-romagnoli** [MaxCunningham19/legal_spellcheck#45]
This involves adding a toggle behaviour to the _Save all_ and _Validate all_ buttons. Label text should change to _Saved_ and _Validated_ on click.

**Comment by petamar** [comment]
@max-romagnoli i added message that said new changes were saved bc it made more sense to me and it is easier to code. Only added this for save button as validate should be seen on the text that was validated? if we want to add message or change that validate button i can add it on tuesday, should be pretty quick.
