### ISSUE TITLE
Bug: Carousel renumbering

### ISSUE THREAD

**Issue by max-romagnoli** [MaxCunningham19/legal_spellcheck#75]
This is a bug that occurs when a user deletes and adds (in this order) a paragraph in the `Carousel`. The issue is solved by refactoring to number the blocks based on their array index, instead of having a separate `block_order` field.

Although small this is urgent and requires a refactoring on both the Backend and Frontend.
This is explained in more details [here in PR #73](https://github.com/MaxCunningham19/legal_spellcheck/pull/73#issuecomment-1448338559).

**Comment by MaxCunningham19** [comment]
how is this bug going?

**Comment by MaxCunningham19** [comment]
Cool sounds good just wanted to check in
