### ISSUE TITLE
Sprint 3: Add a de-highlighting function when a user corrects a misspelt word

### ISSUE THREAD

**Issue by ciannamacmahon** [MaxCunningham19/legal_spellcheck#94]
Currently, the word remains highlighted if a user makes a spelling correction. So once the word is changed and corrected, the word no longer needs to be highlighted.

**Comment by petamar** [comment]
@ciannamacmahon @max-romagnoli do u think it would be fine if we just deactivate highlight on letters deleted. So even if they correct it wrong it would not highlighted? Then if they click validate it would reset anyway. Do we want to compare if word is the one suggested?

**Comment by max-romagnoli** [comment]
Yes that's what we should do. If a user edits inside the highlighted field then then the highlight should disappear.
Then it's up to the user to press the validate again to check if their correction is right/wrong.

**Comment by ciannamacmahon** [comment]
yep I think that's a good way to go. Is it still the case that the Validate All button can only be pressed once, as mentioned in pull request #79? @max-romagnoli @petamar
